org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.250
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=artisanseye
mod_name=Artisan's Eye
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=icu.dreamripples.eye

# TerraFirmaCraft addon dependency (dev/compile pinned to latest; runtime range in neoforge.mods.toml)
tfc_version=4.2.10
tfc_version_range=[4.1.0,4.3)
patchouli_version=1.21.1-92-NEOFORGE
patchouli_version_range=[1.21.1-92-NEOFORGE,)
